using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MQL4CSharp.Base.Enums

{
    public enum Command
    {
        ObjectCreate = 1,
        ObjectName = 2,
        ObjectDelete = 3,
        ObjectsDeleteAll = 4,
        ObjectFind = 5,
        ObjectGetTimeByValue = 6,
        ObjectGetValueByTime = 7,
        ObjectMove = 8,
        ObjectsTotal = 9,
        ObjectGetDouble = 10,
        ObjectGetInteger = 11,
        ObjectGetString = 12,
        ObjectSetDouble = 13,
        ObjectSetInteger = 14,
        ObjectSetString = 15,
        TextSetFont = 16,
        TextOut = 17,
        TextGetSize = 18,
        ObjectDescription = 19,
        ObjectGet = 20,
        ObjectGetFiboDescription = 21,
        ObjectGetShiftByValue = 22,
        ObjectGetValueByShift = 23,
        ObjectSet = 24,
        ObjectSetFiboDescription = 25,
        ObjectSetText = 26,
        ObjectType = 27,

        OrderClose = 28,
        OrderCloseBy = 29,
        OrderClosePrice = 30,
        OrderCloseTime = 31,
        OrderComment = 32,
        OrderCommission = 33,
        OrderDelete = 34,
        OrderExpiration = 35,
        OrderLots = 36,
        OrderMagicNumber = 37,
        OrderModify = 38,
        OrderOpenPrice = 39,
        OrderOpenTime = 40,
        OrderPrint = 41,
        OrderProfit = 42,
        OrderSelect = 43,
        OrderSend = 44,
        OrdersHistoryTotal = 45,
        OrderStopLoss = 46,
        OrdersTotal = 47,
        OrderSwap = 48,
        OrderSymbol = 49,
        OrderTakeProfit = 50,
        OrderTicket = 51,
        OrderType = 52,

        MarketInfo = 53,
        SymbolsTotal = 54,
        SymbolName = 55,
        SymbolSelect = 56,
        SymbolInfoDouble = 57,
        SymbolInfoInteger = 58,
        SymbolInfoString = 59,
        SymbolInfoTick = 60,
        SymbolInfoSessionQuote = 61,
        SymbolInfoSessionTrade = 62,

        AccountInfoDouble = 63,
        AccountInfoInteger = 64,
        AccountInfoString = 65,
        AccountBalance = 66,
        AccountCredit = 67,
        AccountCompany = 68,
        AccountCurrency = 69,
        AccountEquity = 70,
        AccountFreeMargin = 71,
        AccountFreeMarginCheck = 72,
        AccountFreeMarginMode = 73,
        AccountLeverage = 74,
        AccountMargin = 75,
        AccountName = 76,
        AccountNumber = 77,
        AccountProfit = 78,
        AccountServer = 79,
        AccountStopoutLevel = 80,
        AccountStopoutMode = 81,

        iAC = 82,
        iAD = 83,
        iADX = 84,
        iAlligator = 85,
        iAO = 86,
        iATR = 87,
        iBearsPower = 88,
        iBands = 89,
        iBandsOnArray = 90,
        iBullsPower = 91,
        iCCI = 92,
        iCCIOnArray = 93,
        iCustom = 94,
        iDeMarker = 95,
        iEnvelopes = 96,
        iEnvelopesOnArray = 97,
        iForce = 98,
        iFractals = 99,
        iGator = 100,
        iIchimoku = 101,
        iBWMFI = 102,
        iMomentum = 103,
        iMomentumOnArray = 104,
        iMFI = 105,
        iMA = 106,
        iMAOnArray = 107,
        iOsMA = 108,
        iMACD = 109,
        iOBV = 110,
        iSAR = 111,
        iRSI = 112,
        iRSIOnArray = 113,
        iRVI = 114,
        iStdDev = 115,
        iStdDevOnArray = 116,
        iStochastic = 117,
        iWPR = 118,
    }
}
