namespace MQL4CSharp.Base.Enums
{
    public enum ENUM_SIGNAL_INFO_INTEGER
    {
        SIGNAL_INFO_CONFIRMATIONS_DISABLED = 1,
        SIGNAL_INFO_COPY_SLTP = 2,
        SIGNAL_INFO_DEPOSIT_PERCENT = 3,
        SIGNAL_INFO_ID = 4,
        SIGNAL_INFO_SUBSCRIPTION_ENABLED = 5,
        SIGNAL_INFO_TERMS_AGREE = 6,
    }
}
